<a href="https://colab.research.google.com/github/yashpal-ml/Large-Language-Models/blob/main/Copy_of_Pytorch_Breast_Cancer_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [4]:
df.shape

# 33 columns and 569 samples of data

(569, 33)

In [5]:
df = df.drop(['id', 'Unnamed: 32'], axis=1)

In [6]:
df.shape

(569, 31)

In [7]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [8]:
df.iloc[:, 1:].head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)


In [10]:
X_test

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
565        20.13         28.25          131.20     1261.0          0.09780   
313        11.54         10.72           73.73      409.1          0.08597   
439        14.02         15.66           89.59      606.5          0.07966   
93         13.45         18.30           86.60      555.1          0.10220   
223        15.75         20.25          102.60      761.3          0.10250   
..           ...           ...             ...        ...              ...   
491        17.85         13.23          114.60      992.1          0.07838   
17         16.13         20.68          108.10      798.8          0.11700   
220        13.65         13.16           87.88      568.9          0.09646   
418        12.70         12.17           80.88      495.0          0.08785   
362        12.76         18.84           81.87      496.6          0.09676   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
565           0.10340         0.14400             0.097910         0.1752   
313           0.05969         0.01367             0.008907         0.1833   
439           0.05581         0.02087             0.026520         0.1589   
93            0.08165         0.03974             0.027800         0.1638   
223           0.12040         0.11470             0.064620         0.1935   
..                ...             ...                  ...            ...   
491           0.06217         0.04445             0.041780         0.1220   
17            0.20220         0.17220             0.102800         0.2164   
220           0.08711         0.03888             0.025630         0.1360   
418           0.05794         0.02360             0.024020         0.1583   
362           0.07952         0.02688             0.017810         0.1759   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
565                 0.05533  ...         23.69          38.25   
313                 0.06100  ...         12.34          12.87   
439                 0.05586  ...         14.91          19.31   
93                  0.05710  ...         15.10          25.94   
223                 0.06303  ...         19.56          30.29   
..                      ...  ...           ...            ...   
491                 0.05243  ...         19.82          18.42   
17                  0.07356  ...         20.96          31.48   
220                 0.06344  ...         15.34          16.35   
418                 0.06275  ...         13.65          16.92   
362                 0.06183  ...         13.75          25.99   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
565           155.00      1731.0           0.11660            0.19220   
313            81.23       467.8           0.10920            0.16260   
439            96.53       688.9           0.10340            0.10170   
93             97.59       699.4           0.13390            0.17510   
223           125.90      1088.0           0.15520            0.44800   
..               ...         ...               ...                ...   
491           127.10      1210.0           0.09862            0.09976   
17            136.80      1315.0           0.17890            0.42330   
220            99.71       706.2           0.13110            0.24740   
418            88.12       566.9           0.13140            0.16070   
362            87.82       579.7           0.12980            0.18390   

     concavity_worst  concave points_worst  symmetry_worst  \
565          0.32150               0.16280          0.2572   
313          0.08324               0.04715          0.3390   
439          0.06260               0.08216          0.2136   
93           0.13810               0.07911          0.2678   
223          0.39760               0.14790          0.3993   
..               ...                   ...             ...   
491          0.10480               0.08341         

In [11]:
####Scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_test

array([[ 1.72980996,  2.0787492 ,  1.64181938, ...,  0.76312899,
        -0.53293208, -0.97060077],
       [-0.68019917, -2.0039707 , -0.69836245, ..., -0.99019072,
         0.83504098, -0.53001558],
       [ 0.01558926, -0.85344952, -0.0525423 , ..., -0.45941923,
        -1.26207175, -0.93024604],
       ...,
       [-0.08821788, -1.43569708, -0.1221736 , ..., -0.48367614,
        -0.85402111,  0.17978539],
       [-0.35474974, -1.66626711, -0.40721402, ..., -0.45820638,
        -0.19344732,  0.59217754],
       [-0.33791615, -0.11283062, -0.36690116, ..., -0.44486508,
        -0.24528982, -0.63836527]])

In [13]:
X_train

array([[-0.48941847,  0.16664821, -0.46462931, ..., -0.47882475,
        -0.30382167,  0.24667473],
       [ 3.71897931,  0.59285342,  3.71447042, ...,  2.37014921,
        -0.05798789, -0.17179827],
       [ 1.73822675,  0.07814658,  1.63774738, ...,  0.45536946,
         0.27480752, -1.35977513],
       ...,
       [-0.97759262,  0.12472639, -0.98381007, ..., -0.68379563,
        -0.01283474, -0.35643497],
       [ 0.87410241,  1.82256027,  0.82741819, ...,  0.65245684,
         0.19955228,  0.36884452],
       [-0.50625206, -0.30147883, -0.51267898, ..., -0.84237518,
        -0.8105403 , -0.36693826]])

In [14]:
len(X_train)

455

In [15]:
len(X_test)

114

In [16]:
y_train

506    B
180    M
321    M
97     B
423    B
      ..
234    B
189    B
245    B
460    M
480    B
Name: diagnosis, Length: 455, dtype: object

In [17]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [18]:
y_train

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,

In [19]:
y_test

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0])

In [20]:
str(len(y_train)) + ' and ' + str(len(y_test))

'455 and 114'

In [21]:
# All preprocessing so far involved numpy arrays. Now convert these arrays to Pytorch Tensors

X_train_tensor = torch.from_numpy(X_train).to(torch.float32)
X_test_tensor = torch.from_numpy(X_test).to(torch.float32)
y_train_tensor = torch.from_numpy(y_train).to(torch.float32)
y_test_tensor = torch.from_numpy(y_test).to(torch.float32)

In [22]:
X_train_tensor.shape

torch.Size([455, 30])

In [23]:
X_train_tensor.dtype

torch.float32

In [24]:
## Data is now ready

## Define the model

import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self, X):
    super().__init__()
    self.linear = nn.Linear(X.shape[1], 1)
    self.sigmoid = nn.Sigmoid()

    # self.weights = torch.rand((X.shape[1], 1), dtype= torch.float64, requires_grad = True)
    # self.bias = torch.zeros(1, dtype= torch.float64, requires_grad = True)

  def forward(self, X):
    # z = torch.matmul(X, self.weights)+ self.bias
    # y_pred = torch.sigmoid(z)
    # return y_pred
    y_pred = self.sigmoid(self.linear(X))
    return y_pred


  # def loss_function(self, y_pred, y):
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

  #   #Calculate loss
  #   loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
  #   return loss






In [25]:
## Important Parameters
learning_rate = 0.1
epochs = 25

In [26]:
model = MySimpleNN(X_train_tensor)

In [27]:
# model.linear.weight

In [28]:
# model.linear.bias

In [29]:
# model.linear.bias.dtype

In [39]:
## Training Pipeline

# create model - will be an object of the above class MySimpleNN()

from torch import optim

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

loss_function = nn.BCELoss()

model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model(X_train_tensor)
  ## print(y_pred)

  # Calculate Loss
  loss = model.loss_function(y_pred, y_train_tensor.view(-1, 1))
  ## print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  optimizer.zero_grad()

  # Back propagation
  loss.backward()

  # Parameters Update
  # w_grad = model.linear.weight.grad
  # # ## print(w_grad)
  # b_grad = model.linear.bias.grad
  # ## print(b_grad)
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate*w_grad
  #   model.linear.bias -= learning_rate*b_grad


  # Zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  optimizer.step()

  # Print Loss in each Epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")







Epoch: 1, Loss: 0.7264397144317627
Epoch: 2, Loss: 0.7264397144317627
Epoch: 3, Loss: 0.7264397144317627
Epoch: 4, Loss: 0.7264397144317627
Epoch: 5, Loss: 0.7264397144317627
Epoch: 6, Loss: 0.7264397144317627
Epoch: 7, Loss: 0.7264397144317627
Epoch: 8, Loss: 0.7264397144317627
Epoch: 9, Loss: 0.7264397144317627
Epoch: 10, Loss: 0.7264397144317627
Epoch: 11, Loss: 0.7264397144317627
Epoch: 12, Loss: 0.7264397144317627
Epoch: 13, Loss: 0.7264397144317627
Epoch: 14, Loss: 0.7264397144317627
Epoch: 15, Loss: 0.7264397144317627
Epoch: 16, Loss: 0.7264397144317627
Epoch: 17, Loss: 0.7264397144317627
Epoch: 18, Loss: 0.7264397144317627
Epoch: 19, Loss: 0.7264397144317627
Epoch: 20, Loss: 0.7264397144317627
Epoch: 21, Loss: 0.7264397144317627
Epoch: 22, Loss: 0.7264397144317627
Epoch: 23, Loss: 0.7264397144317627
Epoch: 24, Loss: 0.7264397144317627
Epoch: 25, Loss: 0.7264397144317627


In [ ]:
## Training Pipeline

# create model - will be an object of the above class MySimpleNN()
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(6):

  print(f"Before change: {model.bias}")
  # forward pass
  y_pred = model.forward(X_train_tensor)
  ## print(y_pred)

  # Calculate Loss
  loss = model.loss_function(y_pred, y_train_tensor)
  ## print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  # Back propagation
  loss.backward()

  # Parameters Update
  w_grad = model.weights.grad
  ## print(w_grad)
  b_grad = model.bias.grad

  ## print(b_grad)
  with torch.no_grad():
    model.weights -= learning_rate*w_grad
    model.bias -= learning_rate*b_grad

  print(f"After change: {model.bias}")


  # Zero gradients
  model.weights.grad.zero_()
  # model.bias.grad.zero_()

  print(model.bias)

  # Print Loss in each Epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")







Before change: tensor([0.], dtype=torch.float64, requires_grad=True)
After change: tensor([0.0005], dtype=torch.float64, requires_grad=True)
tensor([0.0005], dtype=torch.float64, requires_grad=True)
Epoch: 1, Loss: 3.8726311466191166
Before change: tensor([0.0005], dtype=torch.float64, requires_grad=True)
After change: tensor([0.0008], dtype=torch.float64, requires_grad=True)
tensor([0.0008], dtype=torch.float64, requires_grad=True)
Epoch: 2, Loss: 3.7566116339150306
Before change: tensor([0.0008], dtype=torch.float64, requires_grad=True)
After change: tensor([0.0003], dtype=torch.float64, requires_grad=True)
tensor([0.0003], dtype=torch.float64, requires_grad=True)
Epoch: 3, Loss: 3.6328523152063403
Before change: tensor([0.0003], dtype=torch.float64, requires_grad=True)
After change: tensor([-0.0017], dtype=torch.float64, requires_grad=True)
tensor([-0.0017], dtype=torch.float64, requires_grad=True)
Epoch: 4, Loss: 3.5016733274631626
Before change: tensor([-0.0017], dtype=torch.float

In [ ]:
X_train_tensor[0]

tensor([-0.2116,  0.2458, -0.1582, -0.2854,  0.5680,  0.8393,  0.1807,  0.3935,
         0.6535,  0.7397, -0.0970, -0.6984, -0.1802, -0.1705, -0.6568, -0.1851,
        -0.2934, -0.3389, -0.4068, -0.1659,  0.2774,  0.4140,  0.2245,  0.0899,
         0.8979,  0.8345,  0.5164,  0.5870,  1.4475,  1.1047],
       dtype=torch.float64)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_pred.shape

torch.Size([455, 1])

In [ ]:
model.weights

tensor([[0.1887],
        [0.2855],
        [0.8559],
        [0.8600],
        [0.1108],
        [0.2533],
        [0.9195],
        [0.3725],
        [0.2417],
        [0.1979],
        [0.6355],
        [0.6487],
        [0.3583],
        [0.2072],
        [0.9446],
        [0.5525],
        [0.4658],
        [0.9794],
        [0.5138],
        [0.7944],
        [0.6580],
        [0.5184],
        [0.6000],
        [0.8314],
        [0.3534],
        [0.8237],
        [0.4244],
        [0.4032],
        [0.9704],
        [0.4418]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.weights.shape

torch.Size([30, 1])

In [ ]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)