<a href="https://colab.research.google.com/github/yashpal-ml/Large-Language-Models/blob/main/Pytorch_Breast_Cancer_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [6]:
df.shape

# 33 columns and 569 samples of data

(569, 33)

In [10]:
df = df.drop(['id', 'Unnamed: 32'], axis=1)

In [11]:
df.shape

(569, 31)

In [13]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [12]:
df.iloc[:, 1:].head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)


In [16]:
####Scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
X_train

array([[-0.21162   ,  0.24578265, -0.15823876, ...,  0.58695343,
         1.44747531,  1.10472434],
       [-0.52319011, -1.17698742, -0.52027314, ..., -0.31069834,
        -0.32720777,  0.27877219],
       [-0.67460736,  1.2019577 , -0.62243975, ...,  0.30119577,
        -0.11665215,  0.93336497],
       ...,
       [-1.53535617, -0.54490056, -1.51692752, ..., -1.73016845,
        -0.71489748,  0.3021913 ],
       [ 0.21351304,  1.42721047,  0.15462   , ..., -0.02959978,
        -0.25200933, -0.78822547],
       [-0.34265416,  0.71697468, -0.24556789, ...,  1.34017334,
         0.89267797,  2.33851179]])

In [18]:
len(X_train)

455

In [20]:
len(X_test)

114

In [19]:
y_train

43     M
386    B
537    B
53     M
285    B
      ..
244    M
566    M
391    B
542    B
229    M
Name: diagnosis, Length: 455, dtype: object

In [21]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [25]:
y_train

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [26]:
y_test

array([0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0])

In [24]:
str(len(y_train)) + ' and ' + str(len(y_test))

'455 and 114'

In [27]:
# All preprocessing so far involved numpy arrays. Now convert these arrays to Pytorch Tensors

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [28]:
X_train_tensor.shape

torch.Size([455, 30])

In [29]:
X_train_tensor

tensor([[-0.2116,  0.2458, -0.1582,  ...,  0.5870,  1.4475,  1.1047],
        [-0.5232, -1.1770, -0.5203,  ..., -0.3107, -0.3272,  0.2788],
        [-0.6746,  1.2020, -0.6224,  ...,  0.3012, -0.1167,  0.9334],
        ...,
        [-1.5354, -0.5449, -1.5169,  ..., -1.7302, -0.7149,  0.3022],
        [ 0.2135,  1.4272,  0.1546,  ..., -0.0296, -0.2520, -0.7882],
        [-0.3427,  0.7170, -0.2456,  ...,  1.3402,  0.8927,  2.3385]],
       dtype=torch.float64)

In [54]:
## Data is now ready

## Define the model

class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand((X.shape[1], 1), dtype= torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype= torch.float64, requires_grad = True)

  def forward(self, X):
    z = torch.matmul(X, self.weights)+ self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #Calculate loss
    loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss






In [50]:
## Important Parameters
learning_rate = 0.1
epochs = 25

In [62]:
## Training Pipeline

# create model - will be an object of the above class MySimpleNN()
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(X_train_tensor)
  ## print(y_pred)

  # Calculate Loss
  loss = model.loss_function(y_pred, y_train_tensor)
  ## print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  # Back propagation
  loss.backward()

  # Parameters Update
  w_grad = model.weights.grad
  ## print(w_grad)
  b_grad = model.bias.grad
  ## print(b_grad)
  with torch.no_grad():
    model.weights -= learning_rate*w_grad
    model.bias -= learning_rate*b_grad


  # Zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # Print Loss in each Epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")







Epoch: 1, Loss: 4.0586693753762475
Epoch: 2, Loss: 3.9477285000967495
Epoch: 3, Loss: 3.8327672940371404
Epoch: 4, Loss: 3.7159248483001543
Epoch: 5, Loss: 3.5968321652039847
Epoch: 6, Loss: 3.4717365774258315
Epoch: 7, Loss: 3.336235758049049
Epoch: 8, Loss: 3.2013449421812514
Epoch: 9, Loss: 3.062775032958995
Epoch: 10, Loss: 2.918322342265759
Epoch: 11, Loss: 2.7695462147329795
Epoch: 12, Loss: 2.6185009257469885
Epoch: 13, Loss: 2.467043001276807
Epoch: 14, Loss: 2.314460660147856
Epoch: 15, Loss: 2.163541043282719
Epoch: 16, Loss: 2.010620676192238
Epoch: 17, Loss: 1.8626610490925364
Epoch: 18, Loss: 1.719834443888494
Epoch: 19, Loss: 1.5830006219615629
Epoch: 20, Loss: 1.4478427922135482
Epoch: 21, Loss: 1.3259106233939784
Epoch: 22, Loss: 1.218420170503424
Epoch: 23, Loss: 1.1261767574479946
Epoch: 24, Loss: 1.0493198270174564
Epoch: 25, Loss: 0.9871162364889712


In [66]:
## Training Pipeline

# create model - will be an object of the above class MySimpleNN()
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(6):

  print(f"Before change: {model.bias}")
  # forward pass
  y_pred = model.forward(X_train_tensor)
  ## print(y_pred)

  # Calculate Loss
  loss = model.loss_function(y_pred, y_train_tensor)
  ## print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

  # Back propagation
  loss.backward()

  # Parameters Update
  w_grad = model.weights.grad
  ## print(w_grad)
  b_grad = model.bias.grad

  ## print(b_grad)
  with torch.no_grad():
    model.weights -= learning_rate*w_grad
    model.bias -= learning_rate*b_grad

  print(f"After change: {model.bias}")


  # Zero gradients
  model.weights.grad.zero_()
  # model.bias.grad.zero_()

  print(model.bias)

  # Print Loss in each Epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")







Before change: tensor([0.], dtype=torch.float64, requires_grad=True)
After change: tensor([0.0005], dtype=torch.float64, requires_grad=True)
tensor([0.0005], dtype=torch.float64, requires_grad=True)
Epoch: 1, Loss: 3.8726311466191166
Before change: tensor([0.0005], dtype=torch.float64, requires_grad=True)
After change: tensor([0.0008], dtype=torch.float64, requires_grad=True)
tensor([0.0008], dtype=torch.float64, requires_grad=True)
Epoch: 2, Loss: 3.7566116339150306
Before change: tensor([0.0008], dtype=torch.float64, requires_grad=True)
After change: tensor([0.0003], dtype=torch.float64, requires_grad=True)
tensor([0.0003], dtype=torch.float64, requires_grad=True)
Epoch: 3, Loss: 3.6328523152063403
Before change: tensor([0.0003], dtype=torch.float64, requires_grad=True)
After change: tensor([-0.0017], dtype=torch.float64, requires_grad=True)
tensor([-0.0017], dtype=torch.float64, requires_grad=True)
Epoch: 4, Loss: 3.5016733274631626
Before change: tensor([-0.0017], dtype=torch.float

In [46]:
X_train_tensor[0]

tensor([-0.2116,  0.2458, -0.1582, -0.2854,  0.5680,  0.8393,  0.1807,  0.3935,
         0.6535,  0.7397, -0.0970, -0.6984, -0.1802, -0.1705, -0.6568, -0.1851,
        -0.2934, -0.3389, -0.4068, -0.1659,  0.2774,  0.4140,  0.2245,  0.0899,
         0.8979,  0.8345,  0.5164,  0.5870,  1.4475,  1.1047],
       dtype=torch.float64)

In [43]:
X_train_tensor.shape

torch.Size([455, 30])

In [42]:
y_pred.shape

torch.Size([455, 1])

In [36]:
model.weights

tensor([[0.1887],
        [0.2855],
        [0.8559],
        [0.8600],
        [0.1108],
        [0.2533],
        [0.9195],
        [0.3725],
        [0.2417],
        [0.1979],
        [0.6355],
        [0.6487],
        [0.3583],
        [0.2072],
        [0.9446],
        [0.5525],
        [0.4658],
        [0.9794],
        [0.5138],
        [0.7944],
        [0.6580],
        [0.5184],
        [0.6000],
        [0.8314],
        [0.3534],
        [0.8237],
        [0.4244],
        [0.4032],
        [0.9704],
        [0.4418]], dtype=torch.float64, requires_grad=True)

In [34]:
model.weights.shape

torch.Size([30, 1])

In [35]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)